# Generated by Django 4.0.3 on 2022-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=100)),
                ('plot', models.TextField(max_length=500)),
                ('director', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('metascore', models.CharField(max_length=100)),
                ('imdbrating', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
