# Generated by Django 4.0.3 on 2022-03-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main_app.film'),
            preserve_default=False,
        ),
    ]
