# Generated by Django 4.0.3 on 2022-03-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rating_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
