# Generated by Django 4.0.3 on 2022-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_film_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='img',
            field=models.CharField(default='https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(default='Batman', max_length=100),
            preserve_default=False,
        ),
    ]
